// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadStatus_Result int32

const (
	UploadStatus_OK         UploadStatus_Result = 0
	UploadStatus_QUEUE_FULL UploadStatus_Result = 1
	UploadStatus_DUPLICATE  UploadStatus_Result = 2
	UploadStatus_ERROR      UploadStatus_Result = 3
)

// Enum value maps for UploadStatus_Result.
var (
	UploadStatus_Result_name = map[int32]string{
		0: "OK",
		1: "QUEUE_FULL",
		2: "DUPLICATE",
		3: "ERROR",
	}
	UploadStatus_Result_value = map[string]int32{
		"OK":         0,
		"QUEUE_FULL": 1,
		"DUPLICATE":  2,
		"ERROR":      3,
	}
)

func (x UploadStatus_Result) Enum() *UploadStatus_Result {
	p := new(UploadStatus_Result)
	*p = x
	return p
}

func (x UploadStatus_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_media_proto_enumTypes[0].Descriptor()
}

func (UploadStatus_Result) Type() protoreflect.EnumType {
	return &file_proto_media_proto_enumTypes[0]
}

func (x UploadStatus_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus_Result.Descriptor instead.
func (UploadStatus_Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{1, 0}
}

type VideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	mi := &file_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *VideoChunk) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *VideoChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *VideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        UploadStatus_Result    `protobuf:"varint,1,opt,name=result,proto3,enum=media.UploadStatus_Result" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStatus) GetResult() UploadStatus_Result {
	if x != nil {
		return x.Result
	}
	return UploadStatus_OK
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadStatus) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

var File_proto_media_proto protoreflect.FileDescriptor

const file_proto_media_proto_rawDesc = "" +
	"\n" +
	"\x11proto/media.proto\x12\x05media\"^\n" +
	"\n" +
	"VideoChunk\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb3\x01\n" +
	"\fUploadStatus\x122\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1a.media.UploadStatus.ResultR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\":\n" +
	"\x06Result\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"QUEUE_FULL\x10\x01\x12\r\n" +
	"\tDUPLICATE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032M\n" +
	"\x12MediaUploadService\x127\n" +
	"\vUploadVideo\x12\x11.media.VideoChunk\x1a\x13.media.UploadStatus(\x01B,Z*github.com/example/mediaupload/proto;mediab\x06proto3"

var (
	file_proto_media_proto_rawDescOnce sync.Once
	file_proto_media_proto_rawDescData []byte
)

func file_proto_media_proto_rawDescGZIP() []byte {
	file_proto_media_proto_rawDescOnce.Do(func() {
		file_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)))
	})
	return file_proto_media_proto_rawDescData
}

var file_proto_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_media_proto_goTypes = []any{
	(UploadStatus_Result)(0), // 0: media.UploadStatus.Result
	(*VideoChunk)(nil),       // 1: media.VideoChunk
	(*UploadStatus)(nil),     // 2: media.UploadStatus
}
var file_proto_media_proto_depIdxs = []int32{
	0, // 0: media.UploadStatus.result:type_name -> media.UploadStatus.Result
	1, // 1: media.MediaUploadService.UploadVideo:input_type -> media.VideoChunk
	2, // 2: media.MediaUploadService.UploadVideo:output_type -> media.UploadStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_media_proto_init() }
func file_proto_media_proto_init() {
	if File_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_proto_goTypes,
		DependencyIndexes: file_proto_media_proto_depIdxs,
		EnumInfos:         file_proto_media_proto_enumTypes,
		MessageInfos:      file_proto_media_proto_msgTypes,
	}.Build()
	File_proto_media_proto = out.File
	file_proto_media_proto_goTypes = nil
	file_proto_media_proto_depIdxs = nil
}
