// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/media.proto

package media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaUploadService_UploadVideo_FullMethodName = "/media.MediaUploadService/UploadVideo"
)

// MediaUploadServiceClient is the client API for MediaUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaUploadServiceClient interface {
	// Client-streaming upload: producer sends chunks, server replies once.
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error)
}

type mediaUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaUploadServiceClient(cc grpc.ClientConnInterface) MediaUploadServiceClient {
	return &mediaUploadServiceClient{cc}
}

func (c *mediaUploadServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaUploadService_ServiceDesc.Streams[0], MediaUploadService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaUploadService_UploadVideoClient = grpc.ClientStreamingClient[VideoChunk, UploadStatus]

// MediaUploadServiceServer is the server API for MediaUploadService service.
// All implementations must embed UnimplementedMediaUploadServiceServer
// for forward compatibility.
type MediaUploadServiceServer interface {
	// Client-streaming upload: producer sends chunks, server replies once.
	UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error
	mustEmbedUnimplementedMediaUploadServiceServer()
}

// UnimplementedMediaUploadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaUploadServiceServer struct{}

func (UnimplementedMediaUploadServiceServer) UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error {
	return status.Error(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedMediaUploadServiceServer) mustEmbedUnimplementedMediaUploadServiceServer() {}
func (UnimplementedMediaUploadServiceServer) testEmbeddedByValue()                            {}

// UnsafeMediaUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaUploadServiceServer will
// result in compilation errors.
type UnsafeMediaUploadServiceServer interface {
	mustEmbedUnimplementedMediaUploadServiceServer()
}

func RegisterMediaUploadServiceServer(s grpc.ServiceRegistrar, srv MediaUploadServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaUploadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaUploadService_ServiceDesc, srv)
}

func _MediaUploadService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaUploadServiceServer).UploadVideo(&grpc.GenericServerStream[VideoChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaUploadService_UploadVideoServer = grpc.ClientStreamingServer[VideoChunk, UploadStatus]

// MediaUploadService_ServiceDesc is the grpc.ServiceDesc for MediaUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaUploadService",
	HandlerType: (*MediaUploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _MediaUploadService_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/media.proto",
}
